apiVersion: apps/v1 
kind: Deployment 
metadata: 
  name:  gkelleyflask 
  namespace: kells97 
  labels: 
    app:  gkelleyflask 
spec: 
  selector: 
    matchLabels: 
      app: gkelleyflask 
  replicas: 1 
  strategy: 
    rollingUpdate: 
      maxSurge: 25% 
      maxUnavailable: 25% 
    type: RollingUpdate 
  template: 
    metadata: 
      labels: 
        app:  gkelleyflask 
    spec: 
      containers: 
      - name:  gkelleyflask 
        image:  kells97/flask_app 
        resources: 
          requests: 
            cpu: 100m 
            memory: 100Mi 
          limits: 
            cpu: 100m 
            memory: 100Mi 
        ports: 
        - containerPort:  5000 
          name:  gkelleyflask 
        imagePullPolicy: Always 
      restartPolicy: Always 
 
--- 
apiVersion: v1 
kind: Service 
metadata: 
  name: gkelleyflask 
  namespace: kells97 
spec: 
  selector: 
    app: gkelleyflask 
  type: LoadBalancer 
  sessionAffinity: None 
  sessionAffinityConfig: 
    clientIP: 
      timeoutSeconds: 10800 
  ports: 
  - name: gkelleyflask 
    protocol: TCP 
    port: 80 
    targetPort: 5000 